### ISSUE TITLE
2. Hibernate framework를 사용한 JPA(Java Persistence API) 구현

### ISSUE THREAD

**Issue by LIM-KT** [Park-Sang-soo/pssyak#4]
**Hibernate 통해 JPA 를 구현한다.**

- [x] #5
- [x] JPA 의 개념을 이해한다. - 댓글로 JPA가 뭔지에 대해 너가 확인하고 정리한것을 아주아주 간단하게 정리할것
      : 자바에서 데이터를 저장하기위해 필요한 인터페이스
- [x] Hibernate 개념을 이해한다. - 댓글로 Hibernate가 뭔지에 대해 너가 확인하고 정리한것을 아주아주 간단하게 정리할것
      : JPA의 구현체이며, 대표적인 ORM 프레임워크다.
- [x] Entity, Repository에 대한 개념과 관련 어노테이션의 사용처, 의미들을 이해한다.
      1.1 Entity  
            : 쉽게말해 테이블 전체
      1.2 어노테이션
            : @Entity - 이 클래스가 엔티티임을 의미
              @Getter - 각 필드값을 조회할 수 있는 getter를 자동으로 생성   
              @AllArgsConstructor : 선언된 모든 필드를 파라미터로 갖는 생성자를 자동으로 만들어줌
              @NoArgsConstructor : 파라미터가 아예없는 기본생성자를 자동으로 만들어줌
              @ToString : 선언된 필드들을 모두 출력할 수 있는 toString 메서드를 자동으로 생성
              @Id : 해당 Entity의 PK가 될 값을 지정
       2.1 Repository
            : DB에 접근하는 메서드들을 사용하기 위한 인터페이스.

- [x] 패키지 및 디렉토리 구조를 고민하고 설계한다. ~5/7
- [x] 필요한 Entity, Repository등을 생성한다.  ~5/7
- [x] mybatis를 걷어낸다(안걷어도 되긴함 선택사항)
    : 걷어내지 않기 위해서 Order 패키지로 JPA적용예정
    : Mybatis는 기존 Product 패키지에 적용

**Comment by Park-Sang-soo** [comment]
![image](https://user-images.githubusercontent.com/129250315/235074768-866871b6-8e7a-4c6b-a510-e09a8af5077f.png)

**Comment by LIM-KT** [comment]
1. 위 view에서 키값으로 그럼 ID사용하는지?
   **- 저건 만들어진거고, 실제로 키값은 존재하지 않음.
     view안에 script에서 사용된 db table에서의 키값은 comp_cd임.** 
2. hibernate 관련 어노테이션
- @getter, @AllArgsConstructor, @NoArgsConstructor, @tostring는 lombok 어노테이션임. hibernate와는 관련이 없음
- 다음 항목들에 대해 확실하게 공부하셈, 어노테이션 개념만 본거 같은데 그렇게 하면 안됨, 해당 어노테이션 뿐아니라 어노테이션 내의 옵션이 중요하다. 꼭 어노테이션 + 해당 어노테이션의 옵션들을 공부할 것
- @Table, @GeneratedValue, @Column, @OneToOne, @OneToMany, @ManyToOne, @ManyToMany, @JoinColumn, @SortNatural, @Transient, @DynamicUpdate, @SQLDelete, @Audited, @NotAudited
- 위 어노테이션들중에 @Audited, @NotAudited 이런것들은 이런 프로젝트에서 쓰일일은 없겠지만 "아니 씨벌 마이바티스 두고 왜 이걸 써야함?"이라고 생각할 수 있으니, 뭔지 봐보셈. hibernate envers라는 자동으로 내역을 관리해주는 프로세스가 하이버네이트 안에 내장되어있음, 결국 니가 만약 특정 테이블을 저장/수정/삭제 할때 별도 히스토리테이블을 두어 관리가 가능함(노가다로 안하고 저 envers를 사용해서 자동으로 저장하게 할수 있음)

**Comment by LIM-KT** [comment]
패키지 및 디렉토리는 딱히 고민할건 없고
나는 보통 common.db 에 entity , repository 만들어서 사용함

**Comment by Park-Sang-soo** [comment]
현재 로직에서 주문번호로 DB조회해서 return 받은 값으로 중복체크하는 부분이 있어, 
order라는 패키지를 추가적으로 만들었고, 이 부분을 활용하여 JPA 사용하도록 하겠음.

**Comment by Park-Sang-soo** [comment]
**※ Hibernate관련 어노테이션 개념 정리**
**@Entity**
 : JPA에게 테이블과 매핑함을 알려주는 어노테이션
   DB의 테이블과 매핑(mapping)되는 Java상의 객체 
**@table**
 : 엔티티 클래스에 매핑할 테이블 정보를 제공. 
   name 속성에 지정된 테이블과 매핑! 
   만약 생략할 경우 엔티티 이름이 테이블이름과 자동매핑(대소문자 구분안함)
**@Id**
 : 엔티티의 필드를 테이블의 기본키와 매핑    
**@column**
 : 앤티티의 필드를 테이블의 컬럼에 매핑
   name을 통해 매핑할 테이블의 컬럼을 찾아간다.(기본값은 필드이름)​
**@GeneratedValue**
 : 기본키에 대한 대리키 사용전략을 지정
   AUTO, IDENTITY, SEQUENCE, TABLE
**@Temporal**
 : 날짜 타입을 매핑할때 사용   

**/* 연관관계 매핑 */**
**@OnetoOne**
 : 1:1 - 양방향 : 어느 쪽을 주가될지 정해야함
**@manytoone**
 : N:1 - 양방향 : 서로 참조하면 주가 아닌 쪽에서는 조회 가능
         단방향 : 주인 'N'쪽에서는 '1'쪽 참조 가능하나, 반대는 조회 불가능
**@OneToMany**
 : 1:N - 단방향 : '1'이 연관관계의 주임
**@manytomany**
 : N:N(실무에서는 권장X)
   일대다, 다대일로 풀어서 쓰는게 유연하게 대처할 수 있다.
**@joincolumn**
 : 외래 키를 매핑할때 사용
- 연관관계의 주인만이 외래키를 등록,수정,삭제 가능. 나머지는 조회만!
  mappedBy의 속성으로 주인이 아님을 설정하고, 속성 값으로 주인을 설정.

**@SortNatural**
 : 정렬 기준 어노테이션(자연정렬)
**@transient**
 : 해당 필드는 데이터베이스 컬럼과 매핑이 이루어지지 않고,
   객체에 임시로 어떤 값을 보관하거나 사용하고 싶을 때 사용
**@DynamicUpdate**
 : 변경된 컬럼만 찾아서 업데이트
**@SQLDelete**
 : delete 발행 시 delete sql대신 커스텀 sql을 실행.
   JPA는 기본적으로 hard delete가 기본이지만,
   커스텀 sql을 실행으로 soft delete가 가능
**@Audited**
 : _aud이 붙는 테이블이 생기고 테이블의 이력관리
**@NotAudited**   
 : 테이블의 이력관리 제외

**Comment by LIM-KT** [comment]
mybatis를 걷어낸다(안걷어도 되긴함 선택사항)
: 걷어내지 않기 위해서 Order 패키지로 JPA적용예정
: Mybatis는 기존 Product 패키지에 적용


Order 패키지에 JPA 적용한다는게 이해가 안되는데?
order 관련 테이블만 jpa 적용을 한다는거임?
product는 마이바티스 유지하고???

그럼 안됨
order 건 product건 모두 jpa 적용할것

그리고 common.db 에 entity , repository 로 만들라했는데
니가 말한 구조에서는 어떻게 구조를 만들겠다는 거임?

**Comment by Park-Sang-soo** [comment]
![image](https://user-images.githubusercontent.com/129250315/236112852-73daaad3-5855-44aa-b155-ba4c1c1f367c.png)

**Comment by Park-Sang-soo** [comment]
![image](https://user-images.githubusercontent.com/129250315/236112889-57169710-c54f-4488-9d3d-01a2f180804a.png)

**Comment by LIM-KT** [comment]
PR 안올리니?

**Comment by Park-Sang-soo** [comment]
1. AS-IS
▶ Product패키지만 Mybatis로 구현되었음.
▶ Hibernate 통한 JPA가 구현되어 있지 않음.

2. TO-BE
▶ Hibernate 통한 JPA 구현을 위해 Order패키지 생성
▶ build.gradle에 JPA dependency 추가
▶ application.yml에 JPA 설정 추가
▶ 최초 Response의 값이 단수 건 인줄 알고 작성했다가
    복수 건을 받아야  하므로 List<>로 변경.

3. TEST
▶ Swagger를 통해 "주문번호"와 "주문순번"을 보내 결과 값 확인.
[
  {
    "eaiiNumb": "10000009541603",
    "eaiiType": "I",
    "eaiiYsno": "Y",
    "eaicDate": 1658739745000,
    "eaisDate": 1658739745000,
    "compCd": "003",
    "coOrdNo": "20220724-BA279-B2C",
    "coSeq": "1",
    "tranStat": "Y03",
    "canYn": "N",
    "errNm": null
  },
  {
    "eaiiNumb": "10000009511613",
    "eaiiType": "I",
    "eaiiYsno": "Y",
    "eaicDate": 1658652978000,
    "eaisDate": 1658652978000,
    "compCd": "003",
    "coOrdNo": "20220724-BA279-B2C",
    "coSeq": "1",
    "tranStat": "Y02",
    "canYn": "Y",
    "errNm": null
  },
  {
    "eaiiNumb": "10000009511109",
    "eaiiType": "I",
    "eaiiYsno": "Y",
    "eaicDate": 1658629149000,
    "eaisDate": 1658629149000,
    "compCd": "003",
    "coOrdNo": "20220724-BA279-B2C",
    "coSeq": "1",
    "tranStat": "N01",
    "canYn": "Y",
    "errNm": null
  }
]
▶ Eclipse Console에 찍힌 SQL
Hibernate: 
    select
        orderstate0_.eaii_numb as eaii_numb1_0_,
        orderstate0_.can_yn as can_yn2_0_,
        orderstate0_.co_ord_no as co_ord_no3_0_,
        orderstate0_.co_seq as co_seq4_0_,
        orderstate0_.comp_cd as comp_cd5_0_,
        orderstate0_.eaic_date as eaic_date6_0_,
        orderstate0_.eaii_type as eaii_type7_0_,
        orderstate0_.eaii_ysno as eaii_ysno8_0_,
        orderstate0_.eais_date as eais_date9_0_,
        orderstate0_.err_nm as err_nm10_0_,
        orderstate0_.tran_stat as tran_stat11_0_ 
    from
        inf_tsc_ord_stat_tmp orderstate0_ 
    where
        orderstate0_.co_ord_no=? 
        and orderstate0_.co_seq=?
